network:
  ethernets:
    enp0s3:
        dhcp4: false
        addresses: [172.20.224.211/16]
        gateway4: 172.20.1.2
        nameservers:
          addresses: [172.20.223.100,172.20.224.100]
  version: 2